spring.application.name=demo-learn
spring.profiles.active=dev
# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_learn
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=false
# Liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
# Logging
logging.level.root=warn
logging.level.com.ciet.demo_learn=info
